### ISSUE TITLE
export for android

### ISSUE THREAD

**Issue by arezaee** [godotengine/godot-docs#1408]
hi
I'm newbie in godot, I just download some demos i.e. Platformer 2d and after doing export instructions. export it as  apk file, but when I want to install it in device or emulator it made error INSTALL_PARSE_FAILED_NO_CERTIFICATE

I didn't find any documentation in Godot Docs, neither in stackoverflow
please help me, thanks
update:
I create a hello world sample, and export to android
it installed, but after run force closed with this message:

04-29 11:08:05.517 4379-4379/org.godotengine.hello E/ActivityThread: Activity org.godotengine.godot.Godot has leaked ServiceConnection org.godotengine.godot.payments.PaymentsManager$1@1ceea0a1 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity org.godotengine.godot.Godot has leaked ServiceConnection org.godotengine.godot.payments.PaymentsManager$1@1ceea0a1 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1774)
        at android.app.ContextImpl.bindService(ContextImpl.java:1757)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
        at org.godotengine.godot.payments.PaymentsManager.initService(PaymentsManager.java:79)
        at org.godotengine.godot.Godot.initializeGodot(Godot.java:436)
        at org.godotengine.godot.Godot.onCreate(Godot.java:596)
...

**Comment by mhilbrunner** [comment]
Please see http://docs.godotengine.org/en/latest/getting_started/step_by_step/exporting.html#android

Also, for support the various [Community](https://godotengine.org/community) channels like Discord or IRC are better suited.

**Comment by arezaee** [comment]
thanks, but I have preferred to migrate to libgdx
