### ISSUE TITLE
Unable to 'make html' after last commits

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-docs#2626]
When attempting to `make html`, it errors out, spitting this:
```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/home/michael/Development/Projects/godot-docs/conf.py", line 37, in <module>
    for tag in env_tags.split(','):
AttributeError: 'list' object has no attribute 'split'

make: *** [Makefile:60: html] Error 2
```
I think the cause is one your commits @akien-mga: 2a957dfc7ea3a856349ed321e29735edb724573f

**Comment by akien-mga** [comment]
*grmbl*wth python3*grmbl*

**Comment by akien-mga** [comment]
Right, I messed up assuming that Python had `Array.split()` like GDScript :P
