### ISSUE TITLE
MSbuild issues when compiling godot + mono on debian

### ISSUE THREAD

**Issue by aleph-zer0** [godotengine/godot-docs#4870]
**Your Godot version:** 3.3-stable 

**Issue description:** Issues when trying to compile godot + mono with glue

**URL to the documentation page:** https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html

Hi all,

I am encountering an issue at the second step of the installation when trying to compile with glue. First compilation for the temporary binary and glue generation seem to have executed without issues 

I got the sources from the tar on the main website. 

OS and install details: 
```
uname -a
Linux cube 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

mono --version
Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Wed Apr 17 16:37:36 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       preemptive
	GC:            sgen (concurrent by default)

msbuild -version 
Microsoft (R) Build Engine version 16.6.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.15201%              
```

running the following command 
```bash
 scons p=windows target=release_debug tools=yes module_mono_enabled=yes
```

returns this error

```bash
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Enabling udev support
Checking for `thread_local` support... supported
Mono root directory not found. Using pkg-config instead
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[  0%] build_api_solution(["bin/GodotSharp/Api/Debug/GodotSharp.dll", "bin/GodotSharp/Api/Debug/GodotSharp.pdb", "bin/GodotSharp/Api/Debug/GodotSharp.xml", "bin/GodotSharp/Api/Debug/GodotSharpEditor.dll", "bin/GodotSharp/Api/Debug/GodotSharpEditor.pdb", "bin/GodotSharp/Api/Debug/GodotSharpEditor.xml"], [])
MSBuild path: /usr/bin/msbuild
Microsoft (R) Build Engine version 16.6.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.BadImageFormatException: Could not resolve field token 0x04000389, due to: Could not load type of field 'Microsoft.Build.Execution.BuildManager:_workQueue' (33) due to: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:/usr/lib/mono/msbuild/Current/bin/Microsoft.Build.dll type:BuildManager member:(null)
File name: 'Microsoft.Build'
  at Microsoft.Build.CommandLine.MSBuildApp.BuildProject (System.String projectFile, System.String[] targets, System.String toolsVersion, System.Collections.Generic.Dictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.Dictionary`2[TKey,TValue] restoreProperties, Microsoft.Build.Framework.ILogger[] loggers, Microsoft.Build.Framework.LoggerVerbosity verbosity, Microsoft.Build.CommandLine.DistributedLoggerRecord[] distributedLoggerRecords, System.Int32 cpuCount, System.Boolean enableNodeReuse, System.IO.TextWriter preprocessWriter, System.IO.TextWriter targetsWriter, System.Boolean detailedSummary, System.Collections.Generic.ISet`1[T] warningsAsErrors, System.Collections.Generic.ISet`1[T] warningsAsMessages, System.Boolean enableRestore, Microsoft.Build.Logging.ProfilerLogger profilerLogger, System.Boolean enableProfiler, System.Boolean interactive, System.Boolean isolateProjects, System.Boolean graphBuild, System.Boolean lowPriority, System.String[] inputResultsCaches, System.String outputResultsCache) [0x00616] in <a68a9d5895ee403696730e2dc2e843c3>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x001eb] in <a68a9d5895ee403696730e2dc2e843c3>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.BadImageFormatException: Could not resolve field token 0x04000389, due to: Could not load type of field 'Microsoft.Build.Execution.BuildManager:_workQueue' (33) due to: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:/usr/lib/mono/msbuild/Current/bin/Microsoft.Build.dll type:BuildManager member:(null)
File name: 'Microsoft.Build'
  at Microsoft.Build.CommandLine.MSBuildApp.BuildProject (System.String projectFile, System.String[] targets, System.String toolsVersion, System.Collections.Generic.Dictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.Dictionary`2[TKey,TValue] restoreProperties, Microsoft.Build.Framework.ILogger[] loggers, Microsoft.Build.Framework.LoggerVerbosity verbosity, Microsoft.Build.CommandLine.DistributedLoggerRecord[] distributedLoggerRecords, System.Int32 cpuCount, System.Boolean enableNodeReuse, System.IO.TextWriter preprocessWriter, System.IO.TextWriter targetsWriter, System.Boolean detailedSummary, System.Collections.Generic.ISet`1[T] warningsAsErrors, System.Collections.Generic.ISet`1[T] warningsAsMessages, System.Boolean enableRestore, Microsoft.Build.Logging.ProfilerLogger profilerLogger, System.Boolean enableProfiler, System.Boolean interactive, System.Boolean isolateProjects, System.Boolean graphBuild, System.Boolean lowPriority, System.String[] inputResultsCaches, System.String outputResultsCache) [0x00616] in <a68a9d5895ee403696730e2dc2e843c3>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x00467] in <a68a9d5895ee403696730e2dc2e843c3>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Main () [0x00028] in <a68a9d5895ee403696730e2dc2e843c3>:0 
scons: *** [bin/GodotSharp/Api/Debug/GodotSharp.dll] RuntimeError : 'msbuild' exited with error code: 1
Traceback (most recent call last):
  File "/home/x/tmp/godot/godot-3.3-stable/modules/mono/build_scripts/solution_builder.py", line 106, in run_command
    subprocess.check_call(args, env=env_override)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/msbuild', '/home/x/tmp/godot/godot-3.3-stable/modules/mono/glue/GodotSharp/GodotSharp.sln', '/restore', '/t:Build', '/p:Configuration=Debug', '/p:NoWarn=1591']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/scons/SCons/Action.py", line 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/x/tmp/godot/godot-3.3-stable/modules/mono/build_scripts/api_solution_build.py", line 21, in build_api_solution
    build_solution(env, solution_path, build_config, extra_msbuild_args=extra_msbuild_args)
  File "/home/x/tmp/godot/godot-3.3-stable/modules/mono/build_scripts/solution_builder.py", line 148, in build_solution
    run_command(msbuild_path, msbuild_args, env_override=msbuild_env, name="msbuild")
  File "/home/x/tmp/godot/godot-3.3-stable/modules/mono/build_scripts/solution_builder.py", line 108, in run_command
    raise RuntimeError("'%s' exited with error code: %s" % (name, e.returncode))
RuntimeError: 'msbuild' exited with error code: 1
scons: building terminated because of errors
```

any help or pointer to resources appreciated 
thanks

**Comment by akien-mga** [comment]
Most likely your Mono version is too old. Distro-packaged Mono is typically outdated and may not be sufficient for Godot's requirements.

I would advise removing the Debian mono packages and installing upstream Mono's: https://www.mono-project.com/download/stable/

@godotengine/mono We need to update the version requirement on https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html, what should be the min? 6.x at least but can we be more precise?

**Comment by aleph-zer0** [comment]
thanks it worked just fine

details for people running into similar issue: 
1. i cleaned up all the mono-complete packages from apt-get

2. I compiled mono latest version 6.12.0.122 manually from the tar @ https://download.mono-project.com/sources/mono/ 
compilation instruction here: https://www.mono-project.com/docs/compiling-mono/linux/

```
PREFIX=/usr/local
VERSION=6.12.0.122
tar xvf mono-$VERSION.tar.xz
cd mono-$VERSION
./configure --prefix=$PREFIX
make
make install
```


Note 1: default folder was in /usr/local/ so i kept it but used ```update-alternatives``` to make sure ``` which mono``` was not confused (probably so remnent of previous versions)
Note 2: as akien-mga explained thats more recent than the package shown on https://www.mono-project.com/download/stable/ 

``` bash
mono -V
Mono JIT compiler version 6.12.0.122 (tarball Mon 26 Apr 15:39:29 BST 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

3. had to get a manual update for dotnet-sdk
I got the binaries form here directly  using latest stable v5.0.202
https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.202-linux-x64-binaries

plus bonus script to make sure ```dotnet``` is recognised
```
mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-5.0.202-linux-x64.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
```

4. restarted full compilation for godot + mono (i.e. trashed temp binary and glue and re did all)

**Comment by akien-mga** [comment]
Note that you didn't necessarily need to build Mono from source (unless you wanted to of course), upstream provides repositories for Debian and Ubuntu which should be compatible with your distro.

**Comment by aleph-zer0** [comment]
I believe repo pointed to v5.18 which is where I got it in the first place

**Comment by akien-mga** [comment]
5.18 is what you likely got from the repositories of the *Debian project* which packages Mono: https://packages.debian.org/buster/mono-complete

The upstream *Mono project* also packages Mono for several distros via their own repository, which can be added to your distro. Those repos have the latest stable release: https://www.mono-project.com/download/stable/#download-lin-debian
